language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "Q40p16gJIaQg6IcrmAEvOQmqTsU1QD31L+U/dTEgoCP56R1fKA8w8BRpEIPUtYyskq/tp5UTyRFHoVrseiuE+ceLddeS4RkbjyMZa4GpUnoCyXsn0yyrJn5UH1SRmZKiQBL8V3zoEa+/dcifexRuliQDjYruvKKAu+SAj5SPjzU="

addons:
  coverity_scan:
    project:
      name: "hazendaz/waffle"
      description: "Build submitted via Travis CI"
    notification_email: jeremylandis@hotmail.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true install"
    branch_pattern: coverity_scan

before_script:
- cd Source/JNA

script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mvn clean install -DskipTests=true; fi

after_success:
  - mvn clean test jacoco:report coveralls:report
